version: "3.7"
services:
  webservice:
    build:
      context: .
    container_name: webservice_production_web
    volumes:
      - ./restbucks:/restbucks
    command: >
      sh -c "python manage.py makemigrations & \
             python manage.py migrate & \
             python manage.py collectstatic --no-input --clear & \
             rm -f /restbucks/.coverage &
             gunicorn restbucks.wsgi:application --bind 0.0.0.0:8001"

      - DJANGO_SETTINGS_MODULE=restbucks.settings


  nginx:
    image: nginx:latest
    container_name: nginx_restbucks
    ports:
      - "800:800"
    volumes:
      - ./nginx_production:/etc/nginx/conf.d
      - ./restbucks/static:/restbucks/static
      - ./restbucks/media:/restbucks/media
      - ./nginx_logs/:/var/log/nginx/

  elasticsearch:
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: 7.6.0
    volumes:
      - type: bind
        source: ./elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch
        target: /usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      discovery.type: single-node
    logging:
      driver: none

  logstash:
    build:
      context: logstash/
      args:
        ELK_VERSION: 7.6.0
    volumes:
      - type: bind
        source: ./logstash/config/logstash.yml
        target: /usr/share/logstash/config/logstash.yml
        read_only: true
      - type: bind
        source: ./logstash/pipeline
        target: /usr/share/logstash/pipeline
        read_only: true
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    logging:
      driver: none

  kibana:
    build:
      context: kibana/
      args:
        ELK_VERSION: 7.6.0
    volumes:
      - type: bind
        source: ./kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    logging:
      driver: none

volumes:
  elasticsearch:

