# Generated by Django 3.0.6 on 2020-05-30 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coffee_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('status', models.CharField(choices=[('WA', 'Waiting'), ('PR', 'Prepare'), ('RE', 'Ready'), ('DE', 'Deliver'), ('CA', 'Canceled')], default='WA', max_length=2)),
                ('option_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee_shop.OptionValue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coffee_shop.Product')),
            ],
        ),
    ]
